const DB_KEY='fablab_demo_v1';
const SESSION_KEY='fablab_session_v1';

const seed={
 users:[
  {id:1,name:'مدير النظام',email:'admin@fablab.local',password:'Admin@12345',role:'admin',active:true},
  {id:2,name:'موظف تجريبي',email:'employee@fablab.local',password:'Employee@12345',role:'employee',active:true}
 ],
 students:[],
 programs:[
  {id:1,name:'الروبوتات الذكية',category:'Robotics',max:20,status:'active',description:'تعلّم تصميم وبرمجة الروبوتات عمليًا.'},
  {id:2,name:'نبض الكهرباء',category:'Electronics',max:15,status:'active',description:'أساسيات الكهرباء والدارات وشرائط LED.'},
  {id:3,name:'صناع المستقبل',category:'Innovation',max:24,status:'active',description:'من الفكرة إلى النموذج الأولي بمشاريع عملية.'},
  {id:4,name:'هندسة الإبداع',category:'Engineering',max:18,status:'active',description:'حل المشكلات والهندسة الإبداعية والنمذجة.'},
  {id:5,name:'صناع الواقع',category:'Maker',max:20,status:'active',description:'تجارب تصنيع رقمي ومشاريع تطبيقية.'},
  {id:6,name:'VEX',category:'Robotics',max:20,status:'active',description:'الروبوتات التنافسية وتصميم الروبوت وبرمجته.'},
  {id:7,name:'SPIKE',category:'Robotics',max:20,status:'active',description:'برمجة وتصميم روبوتات LEGO SPIKE.'},
  {id:8,name:'معسكر المبتكر الإلكتروني',category:'Electronics',max:20,status:'active',description:'ابتكار إلكتروني وتصميم نماذج أولية.'}
 ],
 attendance:[],
 volunteers:[],
 trainers:[],
 messages:[],
 activities:[]
};

function loadDB(){
 const raw=localStorage.getItem(DB_KEY);
 if(!raw){localStorage.setItem(DB_KEY,JSON.stringify(seed));return structuredClone(seed)}
 try{return JSON.parse(raw)}catch(e){localStorage.setItem(DB_KEY,JSON.stringify(seed));return structuredClone(seed)}
}
function saveDB(db){localStorage.setItem(DB_KEY,JSON.stringify(db))}
function session(){try{return JSON.parse(localStorage.getItem(SESSION_KEY))}catch{return null}}
function setSession(u){localStorage.setItem(SESSION_KEY,JSON.stringify({id:u.id,name:u.name,email:u.email,role:u.role}))}
function clearSession(){localStorage.removeItem(SESSION_KEY)}
function user(){const s=session();if(!s)return null;const db=loadDB();const u=db.users.find(x=>x.id===s.id);return u?.active?u:null}
function roleLabel(r){return r==='admin'?'مدير النظام':r==='employee'?'موظف':'طالب'}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(msg,type='ok'){const t=document.getElementById('toast');if(!t)return;t.textContent=msg;t.className='toast show '+type;setTimeout(()=>t.className='toast',2400)}
function currentPage(){return document.body.dataset.page||''}
function guard(roles=[]){const u=user();if(!u){location.href='login.html';return null}if(roles.length&&!roles.includes(u.role)){location.href='portal.html';return null}return u}
function counts(db){
 return {students:db.students.length,programs:db.programs.filter(p=>p.status==='active').length,employees:db.users.filter(u=>u.role==='employee').length,volunteers:db.volunteers.length,trainers:db.trainers.length};
}
function updateGlobalHeader(){
 const u=user();document.querySelectorAll('[data-user-name]').forEach(el=>el.textContent=u?.name||'')
 document.querySelectorAll('[data-user-role]').forEach(el=>el.textContent=u?roleLabel(u.role):'')
}
function publicNav(active){
 return `<header class="site-nav"><a class="brand" href="index.html"><img src="assets/fablab-logo.png" alt="Fablab"><span>فاب لاب الأحساء</span></a><nav><a class="${active==='home'?'active':''}" href="index.html">الرئيسية</a><a class="${active==='programs'?'active':''}" href="programs.html">البرامج</a><a class="${active==='about'?'active':''}" href="about.html">عن فاب لاب</a><a class="${active==='contact'?'active':''}" href="contact.html">تواصل معنا</a></nav><div class="nav-actions"><a class="btn light" href="login.html">تسجيل الدخول</a><a class="btn primary" href="register.html">إنشاء حساب طالب</a></div></header>`
}
function shell(inner,active,title='Fablab'){
 document.title=title;
 return `${publicNav(active)}<main>${inner}</main><footer class="site-footer"><span>© 2026 Fablab Al-Ahsa</span><a href="contact.html">تواصل معنا</a></footer><div id="toast" class="toast"></div>`
}
function write(html){document.body.innerHTML=html;updateGlobalHeader()}
function logActivity(db,activity,actor,meta=''){db.activities.unshift({id:Date.now(),activity,actor,meta,time:new Date().toISOString()});db.activities=db.activities.slice(0,30);saveDB(db)}

function renderPublicHome(){
 const db=loadDB();
 const cards=db.programs.filter(p=>p.status==='active').slice(0,6).map(p=>`<article class="program-card"><div class="icon">✦</div><span class="tag">${esc(p.category)}</span><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><a href="programs.html#p${p.id}">التفاصيل</a></article>`).join('');
 const hero=`<section class="hero"><div class="hero-copy"><span class="eyebrow">FAB LAB AL-AHSA</span><h1>مكان تتحول فيه<br><span>الأفكار إلى نماذج.</span></h1><p>منصة فاب لاب تجمع التعلم العملي، التصنيع الرقمي، الروبوتات والإلكترونيات في تجربة واحدة.</p><div class="hero-actions"><a class="btn primary large" href="programs.html">استكشف البرامج</a><a class="btn outline large" href="register.html">سجل كطالب</a></div><div class="hero-badges"><span>✦ مشاريع عملية</span><span>✦ تعلم بالممارسة</span><span>✦ مجتمع مبتكر</span></div></div><div class="hero-art"><div class="orb"></div><img src="assets/fablab-logo-wide.png" alt="Fablab"><div class="floating-card one">🤖 روبوتات</div><div class="floating-card two">⚡ إلكترونيات</div><div class="floating-card three">🧩 تصنيع رقمي</div></div></section>`;
 const section=`<section class="section"><div class="section-head"><div><span class="eyebrow">PROGRAMS</span><h2>اكتشف برامجنا</h2></div><a class="text-link" href="programs.html">عرض جميع البرامج ←</a></div><div class="program-grid">${cards}</div></section>`;
 const roles=`<section class="roles-band"><div><span class="eyebrow">ONE PLATFORM</span><h2>تجربة رقمية متكاملة</h2><p>الزائر يتصفح، الطالب يتابع تجربته، الموظف يدير التشغيل، والمدير يملك أدوات الإدارة.</p></div><div class="role-grid"><div><b>طالب</b><span>بوابة شخصية</span></div><div><b>موظف</b><span>تشغيل ومتابعة</span></div><div><b>مدير</b><span>إدارة كاملة</span></div></div></section>`;
 write(shell(hero+section+roles,'home','الرئيسية | فاب لاب'));
}
function renderPrograms(){const db=loadDB();const rows=db.programs.map(p=>`<article class="program-row" id="p${p.id}"><div class="icon">✦</div><div class="grow"><span class="tag">${esc(p.category)}</span><h2>${esc(p.name)}</h2><p>${esc(p.description)}</p></div><a class="btn primary" href="register.html">سجل في البرنامج</a></article>`).join('');write(shell(`<section class="page-head"><span class="eyebrow">PROGRAMS</span><h1>برامج فاب لاب</h1><p>استكشف البرامج والمسارات التدريبية المتاحة.</p></section><section class="section compact">${rows||'<div class="empty">لا توجد برامج حاليًا.</div>'}</section>`,'programs','البرامج | فاب لاب'))}
function renderAbout(){write(shell(`<section class="page-head"><span class="eyebrow">ABOUT</span><h1>عن فاب لاب الأحساء</h1><p>مساحة عملية للابتكار والتصميم والتصنيع الرقمي.</p></section><section class="content-grid"><div class="info-card"><div class="icon">✦</div><h2>نتعلم بالممارسة</h2><p>برامج ومشاريع تساعد المشارك على الانتقال من الفكرة إلى نموذج أولي قابل للتجربة.</p></div><div class="info-card"><div class="icon">⚙</div><h2>نبني مهارات المستقبل</h2><p>الروبوتات، الإلكترونيات، البرمجة، التصنيع الرقمي والهندسة الإبداعية.</p></div><div class="info-card"><div class="icon">◎</div><h2>مجتمع ابتكار</h2><p>بيئة تجمع الطلاب والمدربين والمتطوعين حول مشاريع وتجارب مشتركة.</p></div><div class="info-card"><div class="icon">⌁</div><h2>منصة رقمية</h2><p>تسجيل وحسابات وبرامج وحضور ومتابعة عبر تجربة رقمية موحدة.</p></div></section>`,'about','عن فاب لاب | فاب لاب'))}
function renderContact(){write(shell(`<section class="page-head"><span class="eyebrow">CONTACT</span><h1>تواصل معنا</h1><p>يسعدنا استقبال الاستفسارات والمقترحات والشراكات.</p></section><section class="form-card"><form id="contactForm"><div class="form-row"><label>الاسم<input name="name" required></label><label>البريد الإلكتروني<input name="email" type="email" required></label></div><label>رقم الجوال<input name="phone"></label><label>رسالتك<textarea name="message" required></textarea></label><button class="btn primary">إرسال الرسالة</button></form></section>`,'contact','تواصل معنا | فاب لاب'));document.getElementById('contactForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),db=loadDB();db.messages.unshift({id:Date.now(),name:fd.get('name'),email:fd.get('email'),phone:fd.get('phone'),message:fd.get('message'),time:new Date().toISOString()});saveDB(db);e.currentTarget.reset();toast('تم إرسال رسالتك بنجاح')})}
function renderLogin(){write(`<div class="auth-wrap"><div class="auth-card"><a class="brand center" href="index.html"><img src="assets/fablab-logo.png" alt="Fablab"><span>فاب لاب الأحساء</span></a><h1>تسجيل الدخول</h1><p class="muted">ادخل إلى بوابتك حسب نوع حسابك.</p><form id="loginForm"><label>البريد الإلكتروني<input type="email" name="email" required></label><label>كلمة المرور<input type="password" name="password" required></label><button class="btn primary full">دخول</button></form><div class="demo-box"><b>حساب المدير التجريبي</b><span>admin@fablab.local</span><span>Admin@12345</span></div><div class="auth-links"><a href="register.html">إنشاء حساب طالب</a><a href="index.html">العودة للموقع</a></div></div></div>`);document.getElementById('loginForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),db=loadDB();const u=db.users.find(x=>x.email.toLowerCase()===String(fd.get('email')).toLowerCase()&&x.password===fd.get('password')&&x.active);if(!u){toast('البريد أو كلمة المرور غير صحيحة','error');return}setSession(u);location.href='portal.html'})}
function renderRegister(){const db=loadDB();const opts=db.programs.filter(p=>p.status==='active').map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');write(`<div class="auth-wrap"><div class="auth-card wide"><a class="brand center" href="index.html"><img src="assets/fablab-logo.png" alt="Fablab"><span>فاب لاب الأحساء</span></a><h1>إنشاء حساب طالب</h1><p class="muted">سجل بنفسك وادخل إلى بوابتك الشخصية.</p><form id="registerForm"><div class="form-row"><label>الاسم الكامل<input name="name" required></label><label>رقم الجوال<input name="phone" required></label></div><div class="form-row"><label>البريد الإلكتروني<input type="email" name="email" required></label><label>العمر<input type="number" name="age" min="7" max="80" required></label></div><div class="form-row"><label>الجنس<select name="gender" required><option value="">اختر</option><option>ذكر</option><option>أنثى</option></select></label><label>البرنامج<select name="program" required><option value="">اختر البرنامج</option>${opts}</select></label></div><div class="form-row"><label>كلمة المرور<input type="password" name="password" minlength="8" required></label><label>تأكيد كلمة المرور<input type="password" name="confirm" minlength="8" required></label></div><button class="btn primary full">إنشاء الحساب والتسجيل</button></form><div class="auth-links"><a href="login.html">لدي حساب</a><a href="index.html">العودة للموقع</a></div></div></div>`);document.getElementById('registerForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),db=loadDB();const email=String(fd.get('email')).toLowerCase();if(fd.get('password')!==fd.get('confirm')){toast('تأكيد كلمة المرور غير مطابق','error');return}if(db.users.some(x=>x.email===email)){toast('هذا البريد مستخدم بالفعل','error');return}const p=db.programs.find(p=>p.id===Number(fd.get('program')));if(!p){toast('اختر برنامجًا','error');return}const registered=db.students.filter(s=>s.programId===p.id).length;if(p.max>0&&registered>=p.max){toast('البرنامج مكتمل','error');return}const uid=Math.max(0,...db.users.map(x=>x.id))+1;const sid=Math.max(0,...db.students.map(x=>x.id))+1;const u={id:uid,name:fd.get('name'),email,password:fd.get('password'),role:'student',active:true};db.users.push(u);db.students.push({id:sid,userId:uid,name:fd.get('name'),phone:fd.get('phone'),age:Number(fd.get('age')),gender:fd.get('gender'),programId:p.id,registeredAt:new Date().toISOString().slice(0,10)});saveDB(db);logActivity(db,'تسجيل طالب جديد',u.name,p.name);setSession(u);location.href='portal.html'})}
function portalSide(role){const items=role==='admin'?[['admin.html','الرئيسية'],['admin-students.html','الطلاب'],['admin-programs.html','البرامج'],['admin-attendance.html','الحضور'],['admin-people.html','المتطوعون والمدربون'],['admin-users.html','المستخدمون'],['admin-reports.html','التقارير'],['admin-settings.html','الإعدادات']]:role==='employee'?[['employee.html','الرئيسية'],['employee-students.html','الطلاب'],['employee-attendance.html','الحضور'],['programs.html','البرامج'],['employee-settings.html','الإعدادات']]:[['student.html','حسابي'],['student-attendance.html','حضوري'],['programs.html','البرامج'],['student-settings.html','الإعدادات']];return `<aside class="portal-side"><a class="brand" href="index.html"><img src="assets/fablab-logo.png"><span>Fablab<small>${roleLabel(role)}</small></span></a><nav>${items.map(([h,t])=>`<a href="${h}" class="side-link">${t}</a>`).join('')}</nav><a class="side-link logout" href="#" data-logout>تسجيل الخروج</a></aside>`}
function portalShell(role,title,body,active=''){const u=guard([role]);if(!u)return;document.body.className='portal-body';document.body.innerHTML=`${portalSide(role)}<main class="portal-main"><header class="portal-top"><div><span class="eyebrow">FABLAB PORTAL</span><h1>${esc(title)}</h1><p>مرحبًا ${esc(u.name)} — ${esc(roleLabel(u.role))}</p></div><a class="icon-btn" href="#" data-logout>↩</a></header>${body}</main><div id="toast" class="toast"></div>`;document.querySelectorAll('[data-logout]').forEach(x=>x.addEventListener('click',e=>{e.preventDefault();clearSession();location.href='index.html'}));}
function adminDashboard(){const db=loadDB(),c=counts(db),activities=db.activities.slice(0,8).map(a=>`<tr><td>${esc(a.activity)}</td><td>${esc(a.actor)}</td><td>${esc(a.meta||'-')}</td><td>${esc(a.time.replace('T',' ').slice(0,16))}</td></tr>`).join('');portalShell('admin','لوحة تحكم المدير',`<div class="kpi-grid"><div class="kpi"><span>إجمالي الطلاب</span><strong>${c.students}</strong></div><div class="kpi"><span>البرامج النشطة</span><strong>${c.programs}</strong></div><div class="kpi"><span>الموظفون</span><strong>${c.employees}</strong></div><div class="kpi"><span>المتطوعون</span><strong>${c.volunteers}</strong></div></div><section class="portal-card"><div class="section-head"><div><span class="eyebrow">CONTROL CENTER</span><h2>إجراءات سريعة</h2></div></div><div class="quick-grid"><a class="quick" href="admin-students.html"><b>إدارة الطلاب</b><span>استعراض وتحديث</span></a><a class="quick" href="admin-programs.html"><b>إدارة البرامج</b><span>إضافة وتعديل وحذف</span></a><a class="quick" href="admin-attendance.html"><b>الحضور</b><span>تسجيل ومتابعة</span></a><a class="quick" href="admin-users.html"><b>المستخدمون</b><span>موظفون وحسابات</span></a></div></section><section class="portal-card"><div class="section-head"><div><span class="eyebrow">ACTIVITY</span><h2>آخر الأنشطة</h2></div></div><div class="table-wrap"><table><thead><tr><th>النشاط</th><th>المستخدم</th><th>المرجع</th><th>الوقت</th></tr></thead><tbody>${activities||'<tr><td colspan="4">لا توجد أنشطة</td></tr>'}</tbody></table></div></section>`) }
function employeeDashboard(){const db=loadDB(),c=counts(db);portalShell('employee','لوحة الموظف',`<div class="kpi-grid"><div class="kpi"><span>الطلاب</span><strong>${c.students}</strong></div><div class="kpi"><span>البرامج</span><strong>${c.programs}</strong></div><div class="kpi"><span>الحضور المسجل</span><strong>${db.attendance.length}</strong></div><div class="kpi"><span>الأنشطة</span><strong>${db.activities.length}</strong></div></div><section class="portal-card"><div class="quick-grid"><a class="quick" href="employee-students.html"><b>الطلاب</b><span>عرض بيانات الطلاب</span></a><a class="quick" href="employee-attendance.html"><b>الحضور</b><span>تسجيل الحضور</span></a><a class="quick" href="programs.html"><b>البرامج</b><span>استعراض البرامج</span></a></div></section>`)}
function studentDashboard(){const u=guard(['student']);if(!u)return;const db=loadDB(),s=db.students.find(x=>x.userId===u.id),p=db.programs.find(x=>x.id===s?.programId),att=db.attendance.filter(x=>x.studentId===s?.id),present=att.filter(x=>x.status==='present').length;portalShell('student','بوابة الطالب',`<section class="hero-card"><div><span class="tag">حساب طالب</span><h2>مرحبًا ${esc(u.name)} 👋</h2><p>هذه بوابتك الشخصية لمتابعة بياناتك وبرنامجك وحضورك.</p></div><a class="btn primary" href="student-settings.html">إعدادات الحساب</a></section><div class="kpi-grid"><div class="kpi"><span>برنامجي</span><strong class="small-value">${esc(p?.name||'غير محدد')}</strong></div><div class="kpi"><span>أيام الحضور</span><strong>${present}</strong></div><div class="kpi"><span>التسجيل</span><strong>#${s?.id||'-'}</strong></div></div><div class="portal-card"><h2>بياناتي</h2><div class="detail-grid"><div><span>الاسم</span><strong>${esc(s?.name||u.name)}</strong></div><div><span>البريد</span><strong>${esc(u.email)}</strong></div><div><span>الجوال</span><strong>${esc(s?.phone||'-')}</strong></div><div><span>العمر</span><strong>${esc(s?.age||'-')}</strong></div></div></div>`)}
function renderListPage(role,type,title,apiKind){const db=loadDB();const list=type==='students'?db.students.map(s=>({...s,program:db.programs.find(p=>p.id===s.programId)?.name||'-'})):type==='programs'?db.programs:apiKind==='vol'?db.volunteers:db.trainers;const rows=list.map(x=>`<tr>${type==='students'?`<td>${esc(x.name)}</td><td>${esc(x.phone)}</td><td>${esc(x.program)}</td><td>${esc(x.age)}</td>`:type==='programs'?`<td>${esc(x.name)}</td><td>${esc(x.category)}</td><td>${esc(x.max)}</td><td><span class="status-chip ok">نشط</span></td>`:`<td>${esc(x.name)}</td><td>${esc(x.phone||'-')}</td><td>${esc(x.role||x.specialty||'-')}</td>`}</tr>`).join('');portalShell(role,title,`<section class="portal-card"><div class="toolbar"><input id="searchBox" placeholder="بحث..."></div><div class="table-wrap"><table><thead><tr>${type==='students'?'<th>الاسم</th><th>الجوال</th><th>البرنامج</th><th>العمر</th>':type==='programs'?'<th>البرنامج</th><th>التصنيف</th><th>السعة</th><th>الحالة</th>':'<th>الاسم</th><th>الجوال</th><th>الدور/التخصص</th>'}</tr></thead><tbody id="listBody">${rows||'<tr><td colspan="5">لا توجد بيانات</td></tr>'}</tbody></table></div></section>`);const sb=document.getElementById('searchBox');if(sb)sb.addEventListener('input',()=>{const q=sb.value.toLowerCase();document.getElementById('listBody').querySelectorAll('tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')})}
function adminPrograms(){const u=guard(['admin']);if(!u)return;const db=loadDB();const body=db.programs.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.category)}</td><td>${p.max}</td><td>${db.students.filter(s=>s.programId===p.id).length}</td><td><button class="small-btn danger" data-del="${p.id}">حذف</button></td></tr>`).join('');portalShell('admin','إدارة البرامج',`<section class="portal-card"><form id="programForm"><div class="form-row"><label>اسم البرنامج<input name="name" required></label><label>التصنيف<input name="category" required></label></div><div class="form-row"><label>الحد الأقصى<input type="number" name="max" min="1" value="20" required></label><label>وصف مختصر<input name="description"></label></div><button class="btn primary">إضافة برنامج</button></form></section><section class="portal-card"><div class="table-wrap"><table><thead><tr><th>البرنامج</th><th>التصنيف</th><th>السعة</th><th>المسجلون</th><th>إجراء</th></tr></thead><tbody>${body}</tbody></table></div></section>`);document.getElementById('programForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),db=loadDB();const id=Math.max(0,...db.programs.map(p=>p.id))+1;db.programs.push({id,name:fd.get('name'),category:fd.get('category'),max:Number(fd.get('max')),status:'active',description:fd.get('description')||''});saveDB(db);logActivity(db,'إضافة برنامج',u.name,fd.get('name'));adminPrograms()});document.querySelectorAll('[data-del]').forEach(b=>b.addEventListener('click',()=>{const id=Number(b.dataset.del),db=loadDB();if(db.students.some(s=>s.programId===id)){toast('لا يمكن حذف برنامج مرتبط بطلاب','error');return}if(!confirm('حذف البرنامج؟'))return;db.programs=db.programs.filter(p=>p.id!==id);saveDB(db);logActivity(db,'حذف برنامج',u.name,String(id));adminPrograms()}))}
function adminUsers(){const u=guard(['admin']);if(!u)return;const db=loadDB();const rows=db.users.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.email)}</td><td>${roleLabel(x.role)}</td><td>${x.active?'نشط':'موقوف'}</td></tr>`).join('');portalShell('admin','إدارة المستخدمين',`<section class="portal-card"><form id="userForm"><div class="form-row"><label>اسم الموظف<input name="name" required></label><label>البريد<input name="email" type="email" required></label></div><div class="form-row"><label>كلمة المرور<input name="password" minlength="8" required></label><label>نوع الحساب<select disabled><option>موظف</option></select></label></div><button class="btn primary">إنشاء حساب موظف</button></form></section><section class="portal-card"><div class="table-wrap"><table><thead><tr><th>الاسم</th><th>البريد</th><th>الصلاحية</th><th>الحالة</th></tr></thead><tbody>${rows}</tbody></table></div></section>`);document.getElementById('userForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),db=loadDB();if(db.users.some(x=>x.email===String(fd.get('email')).toLowerCase())){toast('البريد مستخدم','error');return}const id=Math.max(0,...db.users.map(x=>x.id))+1;db.users.push({id,name:fd.get('name'),email:String(fd.get('email')).toLowerCase(),password:fd.get('password'),role:'employee',active:true});saveDB(db);logActivity(db,'إنشاء حساب موظف',u.name,fd.get('email'));adminUsers()})}
function attendancePage(role){const u=guard(role==='admin'?['admin']:['employee']);if(!u)return;const db=loadDB();const date=new Date().toISOString().slice(0,10);const rows=db.students.map(s=>{const p=db.programs.find(x=>x.id===s.programId);const a=db.attendance.find(x=>x.studentId===s.id&&x.date===date);return `<tr><td>${esc(s.name)}</td><td>${esc(p?.name||'-')}</td><td><input type="checkbox" data-student="${s.id}" ${a?.status==='present'?'checked':''}></td></tr>`}).join('');portalShell(role,'تسجيل الحضور',`<section class="portal-card"><div class="toolbar"><span>التاريخ: ${date}</span><button class="btn primary" id="saveAtt">حفظ الحضور</button></div><div class="table-wrap"><table><thead><tr><th>الطالب</th><th>البرنامج</th><th>حاضر</th></tr></thead><tbody>${rows||'<tr><td colspan="3">لا يوجد طلاب</td></tr>'}</tbody></table></div></section>`);document.getElementById('saveAtt').addEventListener('click',()=>{const db=loadDB();document.querySelectorAll('[data-student]').forEach(cb=>{const sid=Number(cb.dataset.student);db.attendance=db.attendance.filter(a=>!(a.studentId===sid&&a.date===date));db.attendance.push({studentId:sid,date,status:cb.checked?'present':'absent'});});saveDB(db);logActivity(db,'تحديث الحضور',u.name,date);toast('تم حفظ الحضور')})}
function studentAttendance(){const u=guard(['student']);if(!u)return;const db=loadDB(),s=db.students.find(x=>x.userId===u.id);const rows=db.attendance.filter(a=>a.studentId===s?.id).sort((a,b)=>b.date.localeCompare(a.date)).map(a=>`<tr><td>${a.date}</td><td><span class="status-chip ${a.status==='present'?'ok':'bad'}">${a.status==='present'?'حاضر':'غائب'}</span></td></tr>`).join('');portalShell('student','سجل حضوري',`<section class="portal-card"><table><thead><tr><th>التاريخ</th><th>الحالة</th></tr></thead><tbody>${rows||'<tr><td colspan="2">لا يوجد سجل حتى الآن</td></tr>'}</tbody></table></section>`)}
function studentSettings(){const u=guard(['student']);if(!u)return;const db=loadDB(),s=db.students.find(x=>x.userId===u.id);portalShell('student','إعدادات الحساب',`<section class="portal-card"><form id="settingsForm"><label>الاسم<input name="name" value="${esc(u.name)}" required></label><label>رقم الجوال<input name="phone" value="${esc(s?.phone||'')}"></label><label>البريد الإلكتروني<input name="email" value="${esc(u.email)}" type="email" required></label><label>كلمة المرور الجديدة<input name="password" type="password" minlength="8" placeholder="اتركها فارغة لعدم التغيير"></label><button class="btn primary">حفظ التغييرات</button></form></section>`);document.getElementById('settingsForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),db=loadDB(),uu=db.users.find(x=>x.id===u.id),ss=db.students.find(x=>x.userId===u.id);const email=String(fd.get('email')).toLowerCase();if(db.users.some(x=>x.id!==u.id&&x.email===email)){toast('البريد مستخدم بالفعل','error');return}uu.name=fd.get('name');uu.email=email;if(fd.get('password'))uu.password=fd.get('password');ss.name=fd.get('name');ss.phone=fd.get('phone');saveDB(db);logActivity(db,'تحديث حساب طالب',uu.name,uu.email);setSession(uu);toast('تم تحديث الحساب');setTimeout(()=>studentSettings(),250)})}
function employeeSettings(){const u=guard(['employee']);if(!u)return;const db=loadDB();portalShell('employee','إعدادات الحساب',`<section class="portal-card"><form id="es"><label>الاسم<input name="name" value="${esc(u.name)}" required></label><label>البريد الإلكتروني<input name="email" value="${esc(u.email)}" type="email" required></label><label>كلمة المرور الجديدة<input name="password" type="password" minlength="8"></label><button class="btn primary">حفظ التغييرات</button></form></section>`);document.getElementById('es').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),db=loadDB(),uu=db.users.find(x=>x.id===u.id);uu.name=fd.get('name');uu.email=String(fd.get('email')).toLowerCase();if(fd.get('password'))uu.password=fd.get('password');saveDB(db);setSession(uu);toast('تم تحديث الحساب');setTimeout(()=>employeeSettings(),250)})}
function adminSettings(){const u=guard(['admin']);if(!u)return;const db=loadDB();portalShell('admin','إعدادات النظام',`<section class="portal-card"><form id="as"><label>اسم المدير<input name="name" value="${esc(u.name)}" required></label><label>البريد الإلكتروني<input name="email" value="${esc(u.email)}" type="email" required></label><label>كلمة المرور الجديدة<input name="password" type="password" minlength="8"></label><button class="btn primary">حفظ التغييرات</button></form></section><section class="portal-card"><h2>بيانات البيئة</h2><p class="muted">هذه نسخة GitHub Pages تعمل محليًا في المتصفح باستخدام LocalStorage. لا تستخدم بيانات حقيقية.</p></section>`);document.getElementById('as').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),db=loadDB(),uu=db.users.find(x=>x.id===u.id);uu.name=fd.get('name');uu.email=String(fd.get('email')).toLowerCase();if(fd.get('password'))uu.password=fd.get('password');saveDB(db);setSession(uu);toast('تم تحديث الحساب');setTimeout(()=>adminSettings(),250)})}
function adminStudents(){renderListPage('admin','students','إدارة الطلاب')}
function employeeStudents(){renderListPage('employee','students','الطلاب')}
function adminPeople(){const u=guard(['admin']);if(!u)return;const db=loadDB();const vol=db.volunteers.map(v=>`<tr><td>${esc(v.name)}</td><td>${esc(v.phone||'-')}</td><td>${esc(v.role||'-')}</td></tr>`).join('');const tr=db.trainers.map(v=>`<tr><td>${esc(v.name)}</td><td>${esc(v.phone||'-')}</td><td>${esc(v.specialty||'-')}</td></tr>`).join('');portalShell('admin','المتطوعون والمدربون',`<section class="portal-card"><h2>المتطوعون</h2><form id="vform"><div class="form-row"><label>الاسم<input name="name" required></label><label>الجوال<input name="phone"></label></div><label>الدور<input name="role"></label><button class="btn primary">إضافة متطوع</button></form><div class="table-wrap"><table><thead><tr><th>الاسم</th><th>الجوال</th><th>الدور</th></tr></thead><tbody>${vol||'<tr><td colspan="3">لا يوجد</td></tr>'}</tbody></table></div></section><section class="portal-card"><h2>المدربون</h2><form id="tform"><div class="form-row"><label>الاسم<input name="name" required></label><label>الجوال<input name="phone"></label></div><label>التخصص<input name="specialty"></label><button class="btn primary">إضافة مدرب</button></form><div class="table-wrap"><table><thead><tr><th>الاسم</th><th>الجوال</th><th>التخصص</th></tr></thead><tbody>${tr||'<tr><td colspan="3">لا يوجد</td></tr>'}</tbody></table></div></section>`);document.getElementById('vform').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),db=loadDB();db.volunteers.push({id:Date.now(),name:fd.get('name'),phone:fd.get('phone'),role:fd.get('role')});saveDB(db);logActivity(db,'إضافة متطوع',u.name,fd.get('name'));adminPeople()});document.getElementById('tform').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),db=loadDB();db.trainers.push({id:Date.now(),name:fd.get('name'),phone:fd.get('phone'),specialty:fd.get('specialty')});saveDB(db);logActivity(db,'إضافة مدرب',u.name,fd.get('name'));adminPeople()})}
function adminReports(){const u=guard(['admin']);if(!u)return;const db=loadDB(),c=counts(db);portalShell('admin','التقارير',`<div class="kpi-grid"><div class="kpi"><span>الطلاب</span><strong>${c.students}</strong></div><div class="kpi"><span>البرامج</span><strong>${c.programs}</strong></div><div class="kpi"><span>المتطوعون</span><strong>${c.volunteers}</strong></div><div class="kpi"><span>المدربون</span><strong>${c.trainers}</strong></div></div><section class="portal-card"><button class="btn primary" onclick="window.print()">طباعة التقرير</button></section>`)}
function boot(){
 const p=currentPage();
 if(p==='home')renderPublicHome(); else if(p==='programs')renderPrograms(); else if(p==='about')renderAbout(); else if(p==='contact')renderContact(); else if(p==='login')renderLogin(); else if(p==='register')renderRegister(); else if(p==='admin')adminDashboard(); else if(p==='employee')employeeDashboard(); else if(p==='student')studentDashboard(); else if(p==='admin-students')adminStudents(); else if(p==='employee-students')employeeStudents(); else if(p==='admin-programs')adminPrograms(); else if(p==='admin-users')adminUsers(); else if(p==='admin-people')adminPeople(); else if(p==='admin-attendance')attendancePage('admin'); else if(p==='employee-attendance')attendancePage('employee'); else if(p==='student-attendance')studentAttendance(); else if(p==='student-settings')studentSettings(); else if(p==='employee-settings')employeeSettings(); else if(p==='admin-settings')adminSettings(); else if(p==='admin-reports')adminReports(); else if(p==='portal'){const u=user();location.href=u?(u.role==='admin'?'admin.html':u.role==='employee'?'employee.html':'student.html'):'login.html'}
}
document.addEventListener('DOMContentLoaded',boot);
