window.FABLAB_DEMO_PEOPLE=[
{id:'vol-01',name:'مريم التركي',email:'maryam.turki@example.com',phone:'0501234501',department:'الروبوتات',type:'متطوع',programs:['SPIKE Essential']},
{id:'vol-02',name:'عبدالله السالم',email:'abdullah.salem@example.com',phone:'0501234502',department:'الروبوتات',type:'متطوع',programs:['SPIKE Essential']},
{id:'vol-03',name:'سارة العبدالله',email:'sarah.abdullah@example.com',phone:'0501234503',department:'التصنيع الرقمي',type:'متطوع',programs:['التصنيع الرقمي']},
{id:'vol-04',name:'فيصل الحربي',email:'faisal.harbi@example.com',phone:'0501234504',department:'التصنيع الرقمي',type:'متطوع',programs:['التصنيع الرقمي']},
{id:'vol-05',name:'نورة القحطاني',email:'noura.qahtani@example.com',phone:'0501234505',department:'الروبوتات',type:'متطوع',programs:['الروبوتات الذكية']},
{id:'vol-06',name:'محمد العتيبي',email:'mohammed.otaibi@example.com',phone:'0501234506',department:'الروبوتات',type:'متطوع',programs:['الروبوتات الذكية']},
{id:'vol-07',name:'ريم الدوسري',email:'reem.dosari@example.com',phone:'0501234507',department:'الروبوتات',type:'متطوع',programs:['برمج روبوتك']},
{id:'vol-08',name:'خالد الشهري',email:'khaled.shahri@example.com',phone:'0501234508',department:'الروبوتات',type:'متطوع',programs:['برمج روبوتك']},
{id:'vol-09',name:'جود المري',email:'joud.almarri@example.com',phone:'0501234509',department:'الروبوتات',type:'متطوع',programs:['روبوتات VEX العالمية']},
{id:'vol-10',name:'عبدالرحمن الزهراني',email:'abdulrahman.zahrani@example.com',phone:'0501234510',department:'الروبوتات',type:'متطوع',programs:['روبوتات VEX العالمية']},
{id:'vol-11',name:'ليان الحسين',email:'layan.hussein@example.com',phone:'0501234511',department:'الروبوتات',type:'متطوع',programs:['عالم الروبوتات']},
{id:'vol-12',name:'تركي الغامدي',email:'turki.ghamdi@example.com',phone:'0501234512',department:'الروبوتات',type:'متطوع',programs:['عالم الروبوتات']},
{id:'vol-13',name:'هند المطيري',email:'hind.mutairi@example.com',phone:'0501234513',department:'التقنية والابتكار',type:'متطوع',programs:['صناع المستقبل']},
{id:'vol-14',name:'عبدالعزيز الشمري',email:'abdulaziz.shammari@example.com',phone:'0501234514',department:'التقنية والابتكار',type:'متطوع',programs:['صناع المستقبل']},
{id:'vol-15',name:'شهد العيسى',email:'shahad.essa@example.com',phone:'0501234515',department:'التصنيع الرقمي',type:'متطوع',programs:['صناع الواقع']},
{id:'vol-16',name:'سلطان المطلق',email:'sultan.mutlaq@example.com',phone:'0501234516',department:'التصنيع الرقمي',type:'متطوع',programs:['صناع الواقع']},
{id:'vol-17',name:'دانة الهاجري',email:'dana.hajri@example.com',phone:'0501234517',department:'التصنيع الرقمي',type:'متطوع',programs:['هندسة الإبداع']},
{id:'vol-18',name:'يوسف الرشيد',email:'yousef.rashid@example.com',phone:'0501234518',department:'التصنيع الرقمي',type:'متطوع',programs:['هندسة الإبداع']},
{id:'vol-19',name:'لمى العمري',email:'lama.omari@example.com',phone:'0501234519',department:'الإلكترونيات',type:'متطوع',programs:['معسكر المبتكر الإلكتروني']},
{id:'vol-20',name:'مازن السبيعي',email:'mazen.subaie@example.com',phone:'0501234520',department:'الإلكترونيات',type:'متطوع',programs:['معسكر المبتكر الإلكتروني']},
{id:'vol-21',name:'أروى الغامدي',email:'arwa.ghamdi@example.com',phone:'0501234521',department:'الإلكترونيات',type:'متطوع',programs:['نبض الكهرباء']},
{id:'vol-22',name:'راكان العبدالكريم',email:'rakan.abdulkareem@example.com',phone:'0501234522',department:'الإلكترونيات',type:'متطوع',programs:['نبض الكهرباء']},
{id:'vol-23',name:'جنى المطيري',email:'jana.mutairi@example.com',phone:'0501234523',department:'التصنيع الرقمي',type:'متطوع',programs:['التصنيع الرقمي']},
{id:'vol-24',name:'عبدالملك الناصر',email:'abdulmalik.nasser@example.com',phone:'0501234524',department:'التصنيع الرقمي',type:'متطوع',programs:['التصنيع الرقمي']},
{id:'intern-01',name:'محمد الرمضان',email:'mohammed.ramadhan@kfu.edu.sa',phone:'0501234525',department:'الإدارة والمالية',type:'متدرب تعاوني',role:'مساعد إداري ومالي',university:'جامعة الملك فيصل',major:'نظم المعلومات الإدارية',programs:[]},
{id:'intern-02',name:'نورة الحسن',email:'noura.alhassan@kfu.edu.sa',phone:'0501234526',department:'الروبوتات',type:'متدرب تعاوني',role:'متدربة في قسم الروبوتات',university:'جامعة الملك فيصل',major:'نظم المعلومات الإدارية',programs:['الروبوتات الذكية']},
{id:'trn-01',name:'محمد السلمان',email:'mohammed.alsalman@example.com',phone:'0501234527',department:'الروبوتات',type:'مدرب',programs:['الروبوتات الذكية','SPIKE Essential']}
];
