(()=>{
const S='https://nwlqroyagrfuzfrtikln.supabase.co',K='sb_publishable_AqI5cuM8pFcrc2UsiC-1zA_Sullikq7';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const $=s=>document.querySelector(s),now=new Date();let programs=[],registrations=0;
function getUser(){try{return JSON.parse(localStorage.getItem('fablab_session_v1')||'null')}catch{return null}}
function toast(msg){let t=$('#hubToast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function state(p){const t=new Date();t.setHours(0,0,0,0);const s=p.starts_at?new Date(p.starts_at+'T00:00:00'):null,e=p.ends_at?new Date(p.ends_at+'T23:59:59'):s;if(e&&e<t)return'done';if(s&&s>t)return'upcoming';return'current'}
function dateText(p){return p.starts_at?new Date(p.starts_at+'T00:00:00').toLocaleDateString('ar-SA',{day:'numeric',month:'short',year:'numeric'}):'حسب الإعلان'}
async function cloud(){try{const r=await fetch(S+'/rest/v1/programs?select=id,name,description,image,starts_at,ends_at,time_text,price,age_text,location_text,status&archived_at=is.null&order=starts_at.asc',{headers:{apikey:K,Authorization:'Bearer '+K}});if(r.ok)programs=await r.json();const rr=await fetch(S+'/rest/v1/registrations?select=id',{headers:{apikey:K,Authorization:'Bearer '+K}});if(rr.ok){const d=await rr.json();registrations=d.length}}catch(e){console.warn(e)}renderAll()}
function renderAll(){const user=getUser();if($('#hubName'))$('#hubName').textContent=user?.name||'زائر فاب لاب';if($('#hubRole'))$('#hubRole').textContent=user?.role==='admin'?'مدير النظام':user?.role==='employee'?'موظف':'عضو فاب لاب';if($('#statPrograms'))$('#statPrograms').textContent=programs.length||'—';if($('#statRegistrations'))$('#statRegistrations').textContent=registrations||'—';if($('#statUpcoming'))$('#statUpcoming').textContent=programs.filter(p=>state(p)==='upcoming').length||'—';if($('#statProjects'))$('#statProjects').textContent=JSON.parse(localStorage.getItem('fablab_projects_v1')||'[]').length;renderPrograms();renderCalendar();renderNotifications();renderJourney();renderProjects()}
function renderPrograms(){const q=($('#programSearch')?.value||'').trim().toLowerCase(),list=programs.filter(p=>(p.name+' '+(p.description||'')).toLowerCase().includes(q)),shown=list.slice(0,4);const root=$('#hubPrograms');if(!root)return;root.innerHTML=shown.length?shown.map(p=>{const st=state(p),label=st==='current'?'متاح الآن':st==='upcoming'?'قريبًا':'منتهي',cls=st==='current'?'ok':st==='upcoming'?'soon':'done';return`<article class="hub-program">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}">`:''}<div class="hub-program-body"><h3>${esc(p.name)}</h3><p>${esc(p.description||'برنامج تدريبي وتجربة عملية داخل فاب لاب.')}</p><div class="hub-meta"><span>📅 ${esc(dateText(p))}</span><span>🕐 ${esc(p.time_text||'حسب الإعلان')}</span>${p.age_text?`<span>👤 ${esc(p.age_text)}</span>`:''}${p.location_text?`<span>📍 ${esc(p.location_text)}</span>`:''}</div><span class="hub-status ${cls}">${label}</span></div></article>`}).join(''):'<div class="hub-empty">ما لقينا برامج بهذا الاسم.</div>';const old=$('#hubProgramsMore');if(old)old.remove();if(list.length>4){const a=document.createElement('a');a.id='hubProgramsMore';a.href='programs.html';a.className='hub-btn';a.style.cssText='display:block;width:max-content;margin:18px auto 0;background:#eef4ff;color:#2865df;text-decoration:none';a.textContent=`عرض جميع البرامج (${list.length}) ←`;root.parentNode.appendChild(a)}}
function renderCalendar(){const root=$('#hubCalendar');if(!root)return;const y=now.getFullYear(),m=now.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),start=(first.getDay()+6)%7;let h=['الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت','الأحد'].map(x=>`<div class="hub-dayname">${x}</div>`).join('');for(let i=0;i<start;i++)h+='<div class="hub-day muted"></div>';for(let d=1;d<=last.getDate();d++){const ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,events=programs.filter(p=>p.starts_at===ds||p.ends_at===ds);h+=`<div class="hub-day ${d===now.getDate()?'today':''}"><b>${d}</b>${events.slice(0,2).map(p=>`<div class="hub-event" title="${esc(p.name)}">${esc(p.name)}</div>`).join('')}</div>`}root.innerHTML=h;$('#calendarTitle').textContent=now.toLocaleDateString('ar-SA',{month:'long',year:'numeric'})}
function renderNotifications(){const items=[];programs.filter(p=>state(p)==='upcoming').slice(0,3).forEach(p=>items.push(['📣','برنامج قادم',`${p.name} — ${dateText(p)}`]));items.push(['✨','مميزات جديدة','تم إطلاق بوابة التجربة الجديدة لفاب لاب.']);items.push(['🎓','الشهادات','تقدر تتحقق من شهاداتك من قسم الشهادات.']);$('#notifications').innerHTML=items.map(x=>`<div class="hub-list-item"><div class="hub-list-icon">${x[0]}</div><div><b>${esc(x[1])}</b><span>${esc(x[2])}</span></div></div>`).join('')}
function renderJourney(){const projects=JSON.parse(localStorage.getItem('fablab_projects_v1')||'[]'),steps=[['✓','أنشأت حسابك','ابدأ رحلتك التعليمية داخل فاب لاب.'],['1','اختر برنامجًا','استكشف البرامج وسجل في التجربة المناسبة لك.'],['2','احضر وطبّق','الحضور والتطبيق العملي يحولان الفكرة إلى مشروع.'],['3','أنجز مشروعًا',`${projects.length} مشروع مسجل في معرضك حتى الآن.`],['🏆','احصل على إنجازك','أكمل المتطلبات واحصل على شهادة مشاركة أو إتمام.']];$('#journey').innerHTML=steps.map(x=>`<div class="hub-step"><div class="hub-dot">${x[0]}</div><div><b>${esc(x[1])}</b><p>${esc(x[2])}</p></div></div>`).join('')}
function renderProjects(){const projects=JSON.parse(localStorage.getItem('fablab_projects_v1')||'[]');$('#projects').innerHTML=projects.length?projects.slice(-6).reverse().map(p=>`<article class="hub-project"><div class="project-art">${esc(p.icon||'🛠️')}</div><div class="project-body"><h3>${esc(p.name)}</h3><p>${esc(p.description||'مشروع من إنجاز أحد مستفيدي فاب لاب.')}</p></div></article>`).join(''):'<div class="hub-empty">معرض المشاريع جاهز لك — أضف أول مشروعك من الزر بالأسفل.</div>'}
function addProject(){const name=prompt('اسم المشروع؟');if(!name)return;const description=prompt('وصف مختصر؟')||'';const projects=JSON.parse(localStorage.getItem('fablab_projects_v1')||'[]');projects.push({name,description,icon:'🛠️',createdAt:new Date().toISOString()});localStorage.setItem('fablab_projects_v1',JSON.stringify(projects));renderAll();toast('تمت إضافة المشروع إلى معرضك ✨')}
function saveBooking(e){e.preventDefault();const f=new FormData(e.currentTarget),arr=JSON.parse(localStorage.getItem('fablab_bookings_v1')||'[]');arr.push({department:f.get('department'),date:f.get('date'),time:f.get('time'),notes:f.get('notes'),status:'بانتظار المراجعة',createdAt:new Date().toISOString()});localStorage.setItem('fablab_bookings_v1',JSON.stringify(arr));e.currentTarget.reset();toast('تم إرسال طلب الحجز — بانتظار موافقة الإدارة.')}
function saveReview(e){e.preventDefault();const f=new FormData(e.currentTarget);localStorage.setItem('fablab_review_v1',JSON.stringify(Object.fromEntries(f)));e.currentTarget.reset();toast('شكرًا! تم حفظ تقييمك ⭐')}
function setup(){$('#programSearch')?.addEventListener('input',renderPrograms);$('#addProject')?.addEventListener('click',addProject);$('#spBookingForm')?.addEventListener('submit',saveBooking);$('#reviewForm')?.addEventListener('submit',saveReview);document.querySelectorAll('.hub-navlinks a').forEach(a=>a.addEventListener('click',e=>{if(a.getAttribute('href')?.startsWith('#')){e.preventDefault();document.querySelector(a.getAttribute('href'))?.scrollIntoView({behavior:'smooth'})}}));document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',()=>document.querySelector(b.dataset.jump)?.scrollIntoView({behavior:'smooth'})));cloud()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();})();