document.addEventListener('DOMContentLoaded',function(){
 const API='https://nwlqroyagrfuzfrtikln.supabase.co/rest/v1/news_posts';
 const KEY='sb_publishable_AqI5cuM8pFcrc2UsiC-1zA_Sullikq7';
 const style=document.createElement('style');style.textContent='.home-news{padding:0 8vw 75px}.home-news-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:22px}.home-news-head h2{font-size:30px;margin:8px 0}.home-news-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.home-news-card{background:#fff;border:1px solid #e4eaf1;border-radius:17px;overflow:hidden;box-shadow:0 5px 18px #16253a07}.home-news-card img,.home-news-card .hn-placeholder{width:100%;height:150px;object-fit:cover;display:grid;place-items:center;background:#eef4ff;font-size:36px}.home-news-card .hn-body{padding:15px}.home-news-card .hn-meta{font-size:9px;color:#8a95a6;display:flex;justify-content:space-between;gap:8px}.home-news-card h3{font-size:13px;line-height:1.7;margin:9px 0 0;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.home-news-empty{grid-column:1/-1;background:#fff;border:1px dashed #dce4ed;border-radius:17px;padding:25px;text-align:center;color:#7f8b9e;font-size:11px}@media(max-width:900px){.home-news-grid{grid-template-columns:1fr 1fr}}@media(max-width:650px){.home-news{padding:0 6vw 55px}.home-news-grid{grid-template-columns:1fr}.home-news-head h2{font-size:25px}}';document.head.appendChild(style);
 const programsGrid=document.querySelector('.program-grid');if(!programsGrid)return;const section=programsGrid.closest('section');if(!section||document.querySelector('.home-news'))return;
 const wrap=document.createElement('section');wrap.className='home-news';wrap.innerHTML='<div class="home-news-head"><div><span class="eyebrow">LATEST UPDATES</span><h2>آخر أخبار فاب لاب</h2></div><a class="text-link" href="news.html">عرض جميع الأخبار ←</a></div><div class="home-news-grid" id="homeNewsGrid"><div class="home-news-empty">جاري تحميل الأخبار...</div></div>';
 section.insertAdjacentElement('afterend',wrap);
 const grid=wrap.querySelector('#homeNewsGrid');
 fetch(API+'?select=source,title,media_url,permalink,published_at,pinned&is_published=eq.true&show_on_home=eq.true&order=pinned.desc,published_at.desc&limit=4',{headers:{apikey:KEY,Authorization:'Bearer '+KEY}}).then(r=>{if(!r.ok)throw new Error('fetch failed');return r.json()}).then(posts=>{
  if(!posts.length){grid.innerHTML='<div class="home-news-empty">سيظهر هنا أحدث ما ننشره على حسابات فاب لاب.</div>';return}
  grid.innerHTML=posts.map(p=>`<a class="home-news-card" href="${String(p.permalink||'').replace(/"/g,'&quot;')}" target="_blank" rel="noopener">${p.media_url?`<img src="${String(p.media_url).replace(/"/g,'&quot;')}" alt="" loading="lazy">`:'<div class="hn-placeholder">📣</div>'}<div class="hn-body"><div class="hn-meta"><span>${p.source==='instagram'?'Instagram':p.source==='x'?'X':'فاب لاب'}</span><span>${new Date(p.published_at).toLocaleDateString('ar-SA')}</span></div><h3>${String(p.title||'منشور جديد من فاب لاب الأحساء').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}</h3></div></a>`).join('');
 }).catch(()=>{grid.innerHTML='<div class="home-news-empty">أخبار فاب لاب ستظهر هنا عند تفعيل المزامنة.</div>'});
});
