(()=>{
  const INSTAGRAM='https://www.instagram.com/fablabahsa?stkn=Z29jNG1xYjN4aGJz';
  const X='https://x.com/fablabahsa?s=11&t=v0QLVoRjRImTeuuAMjQBVw';
  const TIKTOK='https://www.tiktok.com/@fablabahsa?_r=1&_t=ZS-99b69Y95MHg';
  function add(){
    if(document.body.dataset.page!=='home'||document.getElementById('homeSocialLinks')) return;
    const main=document.querySelector('main'); if(!main) return;
    const section=document.createElement('section'); section.id='homeSocialLinks'; section.className='home-social-links';
    section.innerHTML=`<div class="home-social-inner"><span class="eyebrow">SOCIAL MEDIA</span><h2>تابعنا</h2><p>تابع حسابات فاب لاب الأحساء الرسمية لمعرفة آخر الأخبار والبرامج والفعاليات.</p><div class="home-social-grid">
      <a href="${INSTAGRAM}" target="_blank" rel="noopener noreferrer" aria-label="Instagram"><span class="social-icon instagram-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor"/></svg></span><span><b>Instagram</b><small>@fablabahsa</small></span><em>↗</em></a>
      <a href="${X}" target="_blank" rel="noopener noreferrer" aria-label="X"><span class="social-icon x-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 4l14 16M19 4L5 20" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"/></svg></span><span><b>X</b><small>@fablabahsa</small></span><em>↗</em></a>
      <a class="social-tiktok" href="${TIKTOK}" target="_blank" rel="noopener noreferrer" aria-label="TikTok"><span class="social-icon tiktok-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 4v10.2a4.2 4.2 0 1 1-3.4-4.12" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/><path d="M14 4c.6 2.2 2 3.5 4.2 3.8" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg></span><span><b>TikTok</b><small>@fablabahsa</small></span><em>↗</em></a>
    </div></div>`;
    main.appendChild(section);
    const style=document.createElement('style'); style.textContent=`.home-social-links{margin:18px 0 28px;padding:38px 24px;border:1px solid #294c67;border-radius:26px;background:linear-gradient(145deg,#193b55,#102d43);color:#fff}.home-social-inner{max-width:760px;margin:auto;text-align:center}.home-social-links .eyebrow{color:#7eb3ff}.home-social-links h2{margin:6px 0 8px;font-size:40px;color:#fff}.home-social-links p{margin:0 auto 26px;color:#b9c9d8;font-size:13px;line-height:1.8}.home-social-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;max-width:620px;margin:auto}.home-social-grid a{display:flex;align-items:center;gap:12px;text-align:right;text-decoration:none;color:#fff;background:rgba(255,255,255,.055);border:1px solid rgba(255,255,255,.14);border-radius:18px;padding:15px 16px;min-height:74px;box-sizing:border-box;transition:.18s}.home-social-grid a:hover{border-color:#6ea2e9;background:rgba(255,255,255,.1);transform:translateY(-2px)}.social-icon{width:48px;height:48px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(135deg,#5b8def,#27a99d);color:#fff;flex:none}.social-icon svg{width:25px;height:25px}.home-social-grid a>span:nth-child(2){flex:1}.home-social-grid b{display:block;font-size:15px}.home-social-grid small{display:block;color:#b9c9d8;font-size:11px;margin-top:3px;direction:ltr;text-align:right}.home-social-grid em{font-style:normal;color:#9fc5ff;font-size:20px}.social-tiktok{grid-column:1/-1;max-width:302px;width:100%;justify-self:center}@media(max-width:650px){.home-social-links{margin:16px 0 24px;padding:30px 14px;border-radius:22px}.home-social-links h2{font-size:32px}.home-social-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.home-social-grid a{min-height:105px;padding:12px 8px;flex-direction:column;justify-content:center;text-align:center;gap:7px}.home-social-grid a>span:nth-child(2){flex:none}.home-social-grid small{text-align:center}.home-social-grid em{display:none}.social-tiktok{grid-column:1/-1;max-width:none;width:calc(50% - 5px);justify-self:center}}`;
    document.head.appendChild(style);
  }
  const observer=new MutationObserver(add); observer.observe(document.documentElement,{childList:true,subtree:true}); document.addEventListener('DOMContentLoaded',add); window.addEventListener('load',add);
})();
