(()=>{
  const INSTAGRAM='https://www.instagram.com/fablabahsa?stkn=Z29jNG1xYjN4aGJz';
  const X='https://x.com/fablabahsa?s=11&t=v0QLVoRjRImTeuuAMjQBVw';
  const TIKTOK='https://www.tiktok.com/@fablabahsa?_r=1&_t=ZS-99b69Y95MHg';
  function add(){
    if(document.body.dataset.page!=='home'||document.getElementById('homeSocialLinks')) return;
    const main=document.querySelector('main'); if(!main) return;
    const section=document.createElement('section'); section.id='homeSocialLinks'; section.className='home-social-links';
    section.innerHTML=`<div class="home-social-inner"><div class="section-head"><div><span class="eyebrow">SOCIAL MEDIA</span><h2>تابعنا</h2></div></div><p class="home-social-desc">تابع حسابات فاب لاب الأحساء الرسمية لمعرفة آخر الأخبار والبرامج والفعاليات.</p><div class="home-social-grid">
      <a href="${INSTAGRAM}" target="_blank" rel="noopener noreferrer" aria-label="Instagram"><span class="social-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor"/></svg></span><span><b>Instagram</b><small>@fablabahsa</small></span><em>↗</em></a>
      <a href="${X}" target="_blank" rel="noopener noreferrer" aria-label="X"><span class="social-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 4l14 16M19 4L5 20" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"/></svg></span><span><b>X</b><small>@fablabahsa</small></span><em>↗</em></a>
      <a href="${TIKTOK}" target="_blank" rel="noopener noreferrer" aria-label="TikTok"><span class="social-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 4v10.2a4.2 4.2 0 1 1-3.4-4.12" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/><path d="M14 4c.6 2.2 2 3.5 4.2 3.8" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg></span><span><b>TikTok</b><small>@fablabahsa</small></span><em>↗</em></a>
    </div></div>`;
    main.appendChild(section);
    const style=document.createElement('style'); style.textContent=`.home-social-links{margin:18px 8vw 28px;padding:28px 0;background:transparent;color:#132033}.home-social-inner{max-width:1100px;margin:auto}.home-social-links .section-head{margin-bottom:8px}.home-social-links h2{font-size:30px;margin:8px 0}.home-social-desc{margin:0 0 20px;color:#778295;font-size:12px;line-height:1.8}.home-social-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px}.home-social-grid a{display:flex;align-items:center;gap:13px;text-align:right;text-decoration:none;color:#132033;background:#fff;border:1px solid #e5eaf1;border-radius:17px;padding:18px;min-height:88px;box-sizing:border-box;box-shadow:0 5px 18px #16253a07;transition:.2s}.home-social-grid a:hover{transform:translateY(-3px);box-shadow:0 12px 28px #16253a10;border-color:#d8e0eb}.social-icon{width:44px;height:44px;border-radius:11px;background:#eef4ff;color:#2865df;display:grid;place-items:center;flex:none}.social-icon svg{width:23px;height:23px}.home-social-grid a>span:nth-child(2){flex:1}.home-social-grid b{display:block;font-size:14px}.home-social-grid small{display:block;color:#8994a7;font-size:10px;margin-top:4px;direction:ltr;text-align:right}.home-social-grid em{font-style:normal;color:#2865df;font-size:18px}@media(max-width:650px){.home-social-links{margin:16px 6vw 24px;padding:22px 0}.home-social-grid{grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.home-social-grid a{min-height:96px;padding:10px 6px;flex-direction:column;justify-content:center;text-align:center;gap:7px}.home-social-grid a>span:nth-child(2){flex:none}.home-social-grid small{text-align:center;font-size:9px}.home-social-grid em{display:none}.social-icon{width:40px;height:40px}.social-icon svg{width:21px;height:21px}.home-social-links h2{font-size:26px}.home-social-desc{font-size:11px;margin-bottom:14px}}`;
    document.head.appendChild(style);
  }
  const observer=new MutationObserver(add); observer.observe(document.documentElement,{childList:true,subtree:true}); document.addEventListener('DOMContentLoaded',add); window.addEventListener('load',add);
})();
